### ISSUE TITLE
how to make cluster config persistent in opscenter

### ISSUE THREAD

**Issue by artooro** [datastax/docker-images#16]
Because the cluster config isn't an overwritable config file, the name of the cluster conf file could be anything.
So what I did in order to not have to add the cluster to opscenter each time it reboots is to mount a volume to `/opt/opscenter/conf/clusters` as well.

Perhaps this should be added as a recommended volume mount under "Preserving data" or maybe there is a better way to do this.

**Comment by roberd13** [comment]
@artooro 

How are you restarting OpsCenter?  `docker restart <container_name>`?  
I cannot reproduce the behavior you are describing.   My `cluster_name.conf` persists on reboots and I do not have to add the cluster each time it is rebooted, unless I remove the container and start a new container with the same name.  

Can you give us some more details on exactly the steps you were taking, maybe screenshots prior to mounting `/opt/opscenter/conf/clusters` that caused you to have to add the cluster after a reboot.

Since the `cluster_name.conf` can be named anything if the `cluster_name` is changed in the `cassandra.yaml` we did not include it as an over writable config.  If you want to modify outside of the container, us a custom `cluster_name.conf`  or want to keep the config after removing the container you would need to mount `/opt/opscenter/conf/clusters` so it may be a good idea to add this under the Managing the configuration.

**Comment by artooro** [comment]
@roberd13 that was my point. You should add the note about mounting `/opt/opscenter/conf/clusters` to the documentation so that others know this right off hand. I was adding my solution to the problem in this issue, I don't actually have a problem right now.
