### ISSUE TITLE
Inability to connect via studio docker image using cassandra superuser in browser window

### ISSUE THREAD

**Issue by nadirdbit** [datastax/docker-images#82]
Unable to obtain  a successful test connect via cassandra superuser in browser using link http://127.0.0.1:9091 

![dstudio-connection-failure-20201030](https://user-images.githubusercontent.com/66740875/98304054-d7b46500-1f84-11eb-9a25-28f659e52a8c.png)

**Comment by mjkeeney** [comment]
Nadir, can you please provide details on how you are starting the container? Specific commands and outputs would be useful

**Comment by nadirdbit** [comment]
Hi Michael,

I've attached the requisite output in various files - please let me know if anything else is needed. 

Thank you.

[notes-connectivity-issue-20201110.txt](https://github.com/datastax/docker-images/files/5521756/notes-connectivity-issue-20201110.txt)
[my-dse_cassandra_logs.tar.gz](https://github.com/datastax/docker-images/files/5521757/my-dse_cassandra_logs.tar.gz)
![dstudio-connection-failure-20201110](https://user-images.githubusercontent.com/66740875/98766811-e3e55b80-23a4-11eb-8aba-9abba3b8d085.JPG)

**Comment by roberd13** [comment]
@nadirdbit you are giving the address of your local machine as the host_ip.  This will not work. he containers communicate with each other via the docker networking. You need to pass the actual ip of the DSE node assigned by docker since you did not link them.  Run this command and the IP address you get back put into the host/ip in the studio connection.  `docker inspect my-dse | grep '"IPAddress":'`

We have documented things pretty well in the README of the github repo.  
https://github.com/datastax/docker-images#creating-a-studio-container

Let me know if that resolves your issue.

**Comment by nadirdbit** [comment]
Hi Donnie,

Thanks - issue is now resolved.
